#!/bin/sh

args="$@"
file=$(readlink -f "$args")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
	*\.md) pandoc "$file" -o "$base".pdf \
                 --pdf-engine=xelatex \
                 --var geometry:a4paper \
				 --var geometry:top=3cm \
				 --var geometry:left=2cm \
				 --var geometry:right=2cm \
				 --var geometry:bottom=3cm \
				 --var mainfont="DejaVu Serif" \
                 --var monofont="DejaVu Sans Mono" \
                 -H ~/.config/nvim/vim-compiler/md2pdf.tex \
				 --highlight-style ~/.config/nvim/vim-compiler/pygments.theme
                 ;;
	*\.dot) dot -Tpng "$file" > "$base.png" ;;
esac

