#!/bin/sh

args="$@"
file=$(readlink -f "$args")
dir=$(dirname "$file")
base="${file%.*}"
shebang=$(sed -n 1p "$file")

cd "$dir" || exit

shebangtest() {
	case "$shebang" in
		\#\!*) "$file" ;;
		*) sent "$file" 2>/dev/null & ;;
	esac
}

case "$file" in
	*\.md) pandoc "$file" -o "$base".pdf \
                 --pdf-engine=xelatex \
                 --var geometry:a4paper \
				 --var geometry:top=3cm \
				 --var geometry:left=2cm \
				 --var geometry:right=2cm \
				 --var geometry:bottom=3cm \
				 --var mainfont="DejaVu Serif" \
                 --var monofont="DejaVu Sans Mono" \
                 -H ~/.config/nvim/vim-compiler/md2pdf.tex \
				 --highlight-style ~/.config/nvim/vim-compiler/pygments.theme
                 ;;
	*\.dot) dot -Tpng "$file" > "$base.png" ;;
	*) shebangtest ;;
esac

