#!/bin/sh
# opout: "open output": A general handler for opening a file's intended output.
# I find this useful especially running from vim.

args="$@"
basename="${args%.*}"
READER=zathura

case "$args" in
	*.tex) setsid "$READER" ".output/$basename".pdf >/dev/null 2>&1 & ;;
	*.md|*.rmd|*.ms|*.me|*.mom) setsid "$READER" "$basename".pdf >/dev/null 2>&1 & ;;
	*.html) setsid "$BROWSER" --new-window "$basename".html >/dev/null 2>&1 & ;;
	*.sent) setsid sent "$args" >/dev/null 2>&1 & ;;
	*.dot) sxiv "$basename.png" >/dev/null 2>&1 & ;;
esac
