#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# tex files: Compiles to pdf, including bibliography if necessary
# md files: Compiles to pdf via pandoc
# rmd files: Compiles via R Markdown
# c files: Compiles via whatever compiler is set to cc. Usually gcc.
# py files: runs via python command
# go files: compiles and runs with "go run"
# config.h files: (For suckless utils) recompiles and installs program.
# all others: run `sent` to show a presentation

args="$@"
file=$(readlink -f "$args")
dir=$(dirname "$file")
base="${file%.*}"
shebang=$(sed -n 1p "$file")

cd "$dir" || exit

textype() {
    mkdir .output
    xelatex -output-directory=.output -interaction batchmode vitberget.tex
	}

shebangtest() {
	case "$shebang" in
		\#\!*) "$file" ;;
		*) sent "$file" 2>/dev/null & ;;
	esac
}

case "$file" in
	*\.ms) refer -PS -e "$file" | groff -me -ms -kejpt -T pdf > "$base".pdf ;;
	*\.mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
	*\.rmd) echo "require(rmarkdown); render('$file')" | R -q --vanilla ;;
	*\.tex) textype "$file" ;;
	*\.md) pandoc "$file" -o "$base".pdf \
                 --pdf-engine=xelatex \
                 --var geometry:a4paper \
				 --var geometry:top=3cm \
				 --var geometry:left=2cm \
				 --var geometry:right=2cm \
				 --var geometry:bottom=3cm \
				 --var mainfont="DejaVu Serif" \
                 --var monofont="DejaVu Sans Mono" \
                 -H ~/.config/nvim/vim-compiler/md2pdf.tex \
				 --highlight-style ~/.config/nvim/vim-compiler/pygments.theme
                 ;;
	*config.h) make && sudo make install ;;
        *\.c) cc "$file" -o "$base" && "$base" ;;
	*\.py) python "$file" ;;
	*\.go) go run "$file" ;;
	*\.dot) dot -Tpng "$file" > "$base.png" ;;
	*) shebangtest ;;
esac

